/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamemaps;

import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author victor
 */
public class MunicipiosCampeche extends javax.swing.JFrame {

    /**
     * Creates new form MunicipiosCampeche
     */
    public MunicipiosCampeche() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIco();
    }
    private void setIco() {
        Image imagen;

        try {
            imagen = ImageIO.read( getClass().getClassLoader().getResource( "gamemaps/resources/logo.png" ) );
            setIconImage(imagen);
        } catch( java.io.IOException e ){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelJudulHome = new javax.swing.JLabel();
        Calkini = new javax.swing.JLabel();
        campeche = new javax.swing.JLabel();
        Hecelchakan = new javax.swing.JLabel();
        carmen = new javax.swing.JLabel();
        champoton = new javax.swing.JLabel();
        holpechen = new javax.swing.JLabel();
        palizada = new javax.swing.JLabel();
        tenabo = new javax.swing.JLabel();
        escarcega = new javax.swing.JLabel();
        calakmul = new javax.swing.JLabel();
        candelaria = new javax.swing.JLabel();
        jLabelFormBack = new javax.swing.JLabel();
        candelaria1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(30, 75, 112));
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 470));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 470));

        jLabelJudulHome.setBackground(new java.awt.Color(30, 75, 112));
        jLabelJudulHome.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabelJudulHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelJudulHome.setText("             MUNICIPIOS DE CAMPECHE");
        jLabelJudulHome.setMaximumSize(new java.awt.Dimension(480, 60));
        jLabelJudulHome.setMinimumSize(new java.awt.Dimension(480, 60));
        jLabelJudulHome.setPreferredSize(new java.awt.Dimension(480, 60));

        Calkini.setBackground(new java.awt.Color(255, 255, 255));
        Calkini.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Calkini.setForeground(new java.awt.Color(255, 255, 255));
        Calkini.setText("1. Calkini");
        Calkini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalkiniMouseClicked(evt);
            }
        });

        campeche.setBackground(new java.awt.Color(255, 255, 255));
        campeche.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        campeche.setForeground(new java.awt.Color(255, 255, 255));
        campeche.setText("2. Campeche");
        campeche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campecheMouseClicked(evt);
            }
        });

        Hecelchakan.setBackground(new java.awt.Color(255, 255, 255));
        Hecelchakan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Hecelchakan.setForeground(new java.awt.Color(255, 255, 255));
        Hecelchakan.setText("5. Hecelchakan");
        Hecelchakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HecelchakanMouseClicked(evt);
            }
        });

        carmen.setBackground(new java.awt.Color(255, 255, 255));
        carmen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        carmen.setForeground(new java.awt.Color(255, 255, 255));
        carmen.setText("3. Carmen");
        carmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carmenMouseClicked(evt);
            }
        });

        champoton.setBackground(new java.awt.Color(255, 255, 255));
        champoton.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        champoton.setForeground(new java.awt.Color(255, 255, 255));
        champoton.setText("4. Champoton");
        champoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                champotonMouseClicked(evt);
            }
        });

        holpechen.setBackground(new java.awt.Color(255, 255, 255));
        holpechen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        holpechen.setForeground(new java.awt.Color(255, 255, 255));
        holpechen.setText("6. Holpechen");
        holpechen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                holpechenMouseClicked(evt);
            }
        });

        palizada.setBackground(new java.awt.Color(255, 255, 255));
        palizada.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        palizada.setForeground(new java.awt.Color(255, 255, 255));
        palizada.setText("7. Palizada");
        palizada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                palizadaMouseClicked(evt);
            }
        });

        tenabo.setBackground(new java.awt.Color(255, 255, 255));
        tenabo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tenabo.setForeground(new java.awt.Color(255, 255, 255));
        tenabo.setText("8. Tenabo");
        tenabo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenaboMouseClicked(evt);
            }
        });

        escarcega.setBackground(new java.awt.Color(255, 255, 255));
        escarcega.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        escarcega.setForeground(new java.awt.Color(255, 255, 255));
        escarcega.setText("9. Escarcega");
        escarcega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escarcegaMouseClicked(evt);
            }
        });

        calakmul.setBackground(new java.awt.Color(255, 255, 255));
        calakmul.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        calakmul.setForeground(new java.awt.Color(255, 255, 255));
        calakmul.setText("10. Calakmul");
        calakmul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calakmulMouseClicked(evt);
            }
        });

        candelaria.setBackground(new java.awt.Color(255, 255, 255));
        candelaria.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        candelaria.setForeground(new java.awt.Color(255, 255, 255));
        candelaria.setText("11. Candelaria");
        candelaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candelariaMouseClicked(evt);
            }
        });

        jLabelFormBack.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabelFormBack.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFormBack.setText("<");
        jLabelFormBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFormBackMouseClicked(evt);
            }
        });

        candelaria1.setBackground(new java.awt.Color(255, 255, 255));
        candelaria1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        candelaria1.setForeground(new java.awt.Color(255, 255, 255));
        candelaria1.setText("12. Seybaplaya");
        candelaria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candelaria1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelFormBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelJudulHome, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calakmul, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(escarcega, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenabo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palizada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(holpechen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Calkini, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campeche, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(carmen, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(champoton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(172, 172, 172))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(Hecelchakan)
                                    .addGap(162, 162, 162)))
                            .addComponent(candelaria, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candelaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelJudulHome, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFormBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calkini, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campeche, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carmen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(champoton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hecelchakan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(holpechen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palizada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenabo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escarcega, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calakmul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candelaria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candelaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFormBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFormBackMouseClicked
        new menuCampeche().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabelFormBackMouseClicked

    private void CalkiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalkiniMouseClicked
        JOptionPane.showMessageDialog(null, "En lengua maya significa “Garganta "
                + "del Sol”, conocida como la “Atenas del Camino Real” y llamada “Cuna de las Artesanías Campechanas”.\n"
                +" El municipio de Calkiní se ubica al norte del estado de Campeche; limita al Norte y al Este con el"
                + " Estado de Yucatán; al Sur con el municipio de Hecelchakán y al Oeste con el Golfo de México.");// TODO add your handling code here:
    }//GEN-LAST:event_CalkiniMouseClicked

    private void campecheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campecheMouseClicked
        JOptionPane.showMessageDialog(null, "Campeche es una ciudad puerto de México,"
                + " ubicada en el golfo de México. Es conocida por sus edificios coloniales"
                + " barrocos conservados, la arquitectura militar y el distrito histórico amurallado. \n"
                + " En respuesta a los ataques piratas, la ciudad se fortificó en el siglo XVII y 2 fortalezas sobre cerros son museos en la actualidad.");// TODO add your handling code here:
    }//GEN-LAST:event_campecheMouseClicked

    private void carmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carmenMouseClicked
        JOptionPane.showMessageDialog(null, "Carmen es una ciudad del sureste de México. \n"
                + " Se ubica en la Isla del Carmen, entre el golfo de México y la Laguna de Términos,"
                + " un área protegida con delfines y tortugas. La ciudad es conocida por sus edificios \n"
                + " coloniales, los mariscos y las playas, entre ellas la Playa Norte. ");// TODO add your handling code here:
    }//GEN-LAST:event_carmenMouseClicked

    private void champotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_champotonMouseClicked
        JOptionPane.showMessageDialog(null, "Es una localidad del Estado de Campeche en México, está \n"
                + " localizada al sur de la capital del estado y es cabecera del Municipio de Champotón. ");// TODO add your handling code here:
    }//GEN-LAST:event_champotonMouseClicked

    private void HecelchakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HecelchakanMouseClicked
        JOptionPane.showMessageDialog(null, "El nombre del municipio de Hecelchakán es en lengua Maya que en el español significa "
                + "Sábana del descanso.");// TODO add your handling code here:
    }//GEN-LAST:event_HecelchakanMouseClicked

    private void holpechenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_holpechenMouseClicked
        JOptionPane.showMessageDialog(null, "Hopelchén es una ciudad del estado mexicano de Campeche, \n"
                + " situada al este del territorio cercana a la frontera con el Estado de Yucatán, \n"
                + " en la denominada Región de los Chenes. ");// TODO add your handling code here:
    }//GEN-LAST:event_holpechenMouseClicked

    private void palizadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_palizadaMouseClicked
        JOptionPane.showMessageDialog(null, "Palizada es una localidad del estado mexicano de Campeche, \n"
                + " cabecera del municipio de Palizada; está localizada al suroeste del estado, \n"
                + " en la región de los ríos, cercana a la Laguna de Términos. Cuenta con una extensión \n"
                + " territorial de 2071 kilómetros cuadrados. ");// TODO add your handling code here:
    }//GEN-LAST:event_palizadaMouseClicked

    private void tenaboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenaboMouseClicked
         JOptionPane.showMessageDialog(null, "El municipio de Tenabo se encuentra al norte del Estado de Campeche, \n"
                 + " limita al norte con el municipio de Hecelchakán, al este con el municipio de Hopelchén, \n"
                 + " al sur con el municipio de Campeche y al oeste con el Golfo de México, en la región conocida como «Camino Real». ");// TODO add your handling code here:
    }//GEN-LAST:event_tenaboMouseClicked

    private void escarcegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escarcegaMouseClicked
        JOptionPane.showMessageDialog(null, "Escárcega es una ciudad del estado mexicano de Campeche, \n"
                + " situada en el centro del estado. Es un importante nudo de comunicaciones, \n"
                + " tanto de carreteras como de ferrocarril. Su origen se dio como estación de ferrocarril \n"
                + " y campamento de explotación chiclera y de palo de tinte.");// TODO add your handling code here:
    }//GEN-LAST:event_escarcegaMouseClicked

    private void calakmulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calakmulMouseClicked
        JOptionPane.showMessageDialog(null, "Es uno de los 12 municipios del estado de Campeche y fue establecido \n"
                + " por decreto del 31 de diciembre de 1996 segregándolo del Municipio de Hopelchen, \n"
                + " su cabecera es la población de Xpujil. ");// TODO add your handling code here:
    }//GEN-LAST:event_calakmulMouseClicked

    private void candelariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candelariaMouseClicked
        JOptionPane.showMessageDialog(null, "Al sur del estado de Campeche, en medio de la selva tropical, se encuentra Candelaria, \n"
                + " declarado el onceavo municipio de dicho estado el 19 de junio de 1998. Lo atraviesa el río más caudaloso de la región, \n"
                + " que lleva también el nombre de Candelaria.");// TODO add your handling code here:
    }//GEN-LAST:event_candelariaMouseClicked

    private void candelaria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candelaria1MouseClicked
        JOptionPane.showMessageDialog(null, "Seybaplaya es un puerto de pesca, industrial y comercial y cabecera del municipio homónimo, \n"
                + " en el estado de Campeche, México. La población se asienta en la porción norte de la pequeña bahía limitada al sur por \n"
                + " Punta Sihoplaya");// TODO add your handling code here:
    }//GEN-LAST:event_candelaria1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MunicipiosCampeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MunicipiosCampeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MunicipiosCampeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MunicipiosCampeche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MunicipiosCampeche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Calkini;
    private javax.swing.JLabel Hecelchakan;
    private javax.swing.JLabel calakmul;
    private javax.swing.JLabel campeche;
    private javax.swing.JLabel candelaria;
    private javax.swing.JLabel candelaria1;
    private javax.swing.JLabel carmen;
    private javax.swing.JLabel champoton;
    private javax.swing.JLabel escarcega;
    private javax.swing.JLabel holpechen;
    private javax.swing.JLabel jLabelFormBack;
    private javax.swing.JLabel jLabelJudulHome;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel palizada;
    private javax.swing.JLabel tenabo;
    // End of variables declaration//GEN-END:variables
}
